<?php
header('Content-Type: application/json; charset=utf-8'); header('Access-Control-Allow-Origin: *'); header('Access-Control-Allow-Headers: Content-Type'); header('Access-Control-Allow-Methods: GET,POST,PUT,PATCH,OPTIONS');
if($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}
function body(){return json_decode(file_get_contents('php://input'),true)?:[];}
function out($x,$c=200){http_response_code($c);echo json_encode($x,JSON_UNESCAPED_UNICODE);exit;}
function db(){static $p;if($p)return $p;$u=parse_url(getenv('DATABASE_URL'));if(!$u)throw new Exception('DATABASE_URL não configurada.');$p=new PDO('pgsql:host='.$u['host'].';port='.($u['port']??5432).';dbname='.ltrim($u['path']??'','/'),$u['user'],$u['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$p->exec("CREATE TABLE IF NOT EXISTS customers(id SERIAL PRIMARY KEY,name TEXT NOT NULL,phone TEXT UNIQUE NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS barbers(id SERIAL PRIMARY KEY,name TEXT NOT NULL,specialty TEXT DEFAULT '',rating NUMERIC(2,1) DEFAULT 5,active BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS services(id SERIAL PRIMARY KEY,name TEXT NOT NULL,duration INTEGER NOT NULL DEFAULT 30,price NUMERIC(10,2) NOT NULL DEFAULT 0,active BOOLEAN DEFAULT TRUE);
DO \$\$ BEGIN CREATE TYPE appointment_status AS ENUM ('Pendente','Confirmado','Concluído','Cancelado'); EXCEPTION WHEN duplicate_object THEN NULL; END \$\$;
CREATE TABLE IF NOT EXISTS appointments(id SERIAL PRIMARY KEY,customer_id INTEGER REFERENCES customers(id),barber_id INTEGER REFERENCES barbers(id),service_id INTEGER REFERENCES services(id),date DATE NOT NULL,time TIME NOT NULL,status appointment_status NOT NULL DEFAULT 'Pendente',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE UNIQUE INDEX IF NOT EXISTS ux_appointment_slot ON appointments(barber_id,date,time) WHERE status<>'Cancelado';
CREATE TABLE IF NOT EXISTS barber_schedules(id SERIAL PRIMARY KEY,barber_id INTEGER REFERENCES barbers(id) ON DELETE CASCADE,day_of_week INTEGER NOT NULL,start_time TIME,end_time TIME,break_start TIME,break_end TIME,active BOOLEAN DEFAULT TRUE,UNIQUE(barber_id,day_of_week));");
if(!$p->query("SELECT COUNT(*) FROM services")->fetchColumn())$p->exec("INSERT INTO services(name,duration,price) VALUES('Corte Masculino',30,35),('Barba Tradicional',20,25),('Combo Corte + Barba',50,55),('Sobrancelha',15,15),('Pigmentação de Barba',30,40)");
if(!$p->query("SELECT COUNT(*) FROM barbers")->fetchColumn())$p->exec("INSERT INTO barbers(name,specialty,rating) VALUES('Lucas','Especialista em degradê',4.9),('Rafael','Barba e bigode',4.8),('Thiago','Corte masculino',4.7),('Matheus','Estilo clássico',4.9)");
$p->exec("INSERT INTO barber_schedules(barber_id,day_of_week,start_time,end_time,break_start,break_end,active) SELECT b.id,d,'09:00','18:00','12:30','14:00',(d BETWEEN 1 AND 6) FROM barbers b CROSS JOIN generate_series(0,6)d ON CONFLICT DO NOTHING");return $p;}
try{$p=db();$m=$_SERVER['REQUEST_METHOD'];$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);
if($path==='/api/health')out(['ok'=>true,'service'=>'Studio A.A API']);
if($m==='GET'&&$path==='/api/services')out($p->query("SELECT id,name,duration,price,active FROM services ORDER BY id")->fetchAll());
if($m==='GET'&&$path==='/api/barbers')out($p->query("SELECT id,name,specialty,rating,active FROM barbers ORDER BY id")->fetchAll());
if($m==='POST'&&$path==='/api/barbers'){$x=body();$q=$p->prepare("INSERT INTO barbers(name,specialty,rating,active) VALUES(?,?,?,?) RETURNING *");$q->execute([$x['name'],$x['specialty']??'',$x['rating']??5,$x['active']??true]);out($q->fetch(),201);}
if($m==='PUT'&&preg_match('#^/api/barbers/(\d+)$#',$path,$z)){$x=body();$q=$p->prepare("UPDATE barbers SET name=?,specialty=?,rating=?,active=? WHERE id=? RETURNING *");$q->execute([$x['name'],$x['specialty']??'',$x['rating']??5,$x['active']??true,$z[1]]);out($q->fetch());}
if($m==='POST'&&$path==='/api/services'){$x=body();$q=$p->prepare("INSERT INTO services(name,duration,price,active) VALUES(?,?,?,?) RETURNING *");$q->execute([$x['name'],(int)($x['duration']??30),(float)($x['price']??0),$x['active']??true]);out($q->fetch(),201);}
if($m==='PUT'&&preg_match('#^/api/services/(\d+)$#',$path,$z)){$x=body();$q=$p->prepare("UPDATE services SET name=?,duration=?,price=?,active=? WHERE id=? RETURNING *");$q->execute([$x['name'],(int)$x['duration'],(float)$x['price'],$x['active']??true,$z[1]]);out($q->fetch());}
if($m==='GET'&&$path==='/api/schedules'){$q=$p->prepare("SELECT day_of_week,start_time::text,end_time::text,break_start::text,break_end::text,active FROM barber_schedules WHERE barber_id=? ORDER BY day_of_week");$q->execute([(int)($_GET['barber_id']??0)]);out($q->fetchAll());}
if($m==='PUT'&&$path==='/api/schedules'){$x=body();$p->beginTransaction();$q=$p->prepare("DELETE FROM barber_schedules WHERE barber_id=?");$q->execute([(int)$x['barber_id']]);$q=$p->prepare("INSERT INTO barber_schedules(barber_id,day_of_week,start_time,end_time,break_start,break_end,active) VALUES(?,?,?,?,?,?,?)");foreach($x['schedules']??[] as $r)$q->execute([(int)$x['barber_id'],(int)$r['day_of_week'],$r['start_time']?:null,$r['end_time']?:null,$r['break_start']?:null,$r['break_end']?:null,(bool)$r['active']]);$p->commit();out(['ok'=>true]);}
if($m==='GET'&&$path==='/api/availability'){$q=$p->prepare("SELECT id,barber_id,date,time::text,status FROM appointments WHERE barber_id=? AND date=? AND status<>'Cancelado' ORDER BY time");$q->execute([(int)($_GET['barber_id']??0),$_GET['date']??'']);out($q->fetchAll());}
if($m==='POST'&&$path==='/api/appointments'){$x=body();$p->beginTransaction();$q=$p->prepare("SELECT id FROM appointments WHERE barber_id=? AND date=? AND time=? AND status<>'Cancelado' FOR UPDATE");$q->execute([(int)$x['barber_id'],$x['date'],$x['time']]);if($q->fetch()){$p->rollBack();out(['error'=>'Horário já ocupado.'],409);}$q=$p->prepare("INSERT INTO customers(name,phone) VALUES(?,?) ON CONFLICT(phone) DO UPDATE SET name=EXCLUDED.name RETURNING id");$q->execute([$x['customer_name'],$x['customer_phone']]);$cid=$q->fetchColumn();$q=$p->prepare("INSERT INTO appointments(customer_id,barber_id,service_id,date,time) VALUES(?,?,?,?,?) RETURNING id");$q->execute([$cid,$x['barber_id'],$x['service_id'],$x['date'],$x['time']]);$id=$q->fetchColumn();$p->commit();out(['id'=>(int)$id],201);}
if($m==='PATCH'&&preg_match('#^/api/appointments/(\d+)$#',$path,$z)){$x=body();$q=$p->prepare("UPDATE appointments SET status=? WHERE id=? RETURNING id,status");$q->execute([$x['status']??'Cancelado',$z[1]]);out($q->fetch());}
if($m==='GET'&&$path==='/api/admin/dashboard'){$today=date('Y-m-d');$d=['today'=>(int)$p->query("SELECT COUNT(*) FROM appointments WHERE date='$today' AND status<>'Cancelado'")->fetchColumn(),'clients'=>(int)$p->query("SELECT COUNT(*) FROM customers")->fetchColumn(),'barbers'=>(int)$p->query("SELECT COUNT(*) FROM barbers WHERE active")->fetchColumn(),'services'=>(int)$p->query("SELECT COUNT(*) FROM services WHERE active")->fetchColumn()];$d['appointments']=$p->query("SELECT a.id,a.date,a.time::text,a.status,c.name customer_name,c.phone customer_phone,b.name barber_name,b.id barber_id,s.name service_name FROM appointments a JOIN customers c ON c.id=a.customer_id JOIN barbers b ON b.id=a.barber_id JOIN services s ON s.id=a.service_id ORDER BY a.date DESC,a.time DESC")->fetchAll();out($d);}
out(['error'=>'Rota não encontrada'],404);
}catch(Throwable $e){if(isset($p)&&$p->inTransaction())$p->rollBack();out(['error'=>$e->getMessage()],500);}
?>
